### ISSUE TITLE
AttributeError: type object 'NewBase' has no attribute '__typeid__'

### ISSUE THREAD

**Issue by stoarca** [SecurityInnovation/PGPy#150]
I get this error when trying to import pgpy on Ubuntu 14.04 LTS python 2.7.6 inside vagrant. Any idea why?
It works on Ubuntu 12.04 LTS python 2.7.3 on the host.

Stack trace:

    >>> import pgpy
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/pgpy/__init__.py", line 8, in <module>
        from . import constants
      File "/usr/local/lib/python2.7/dist-packages/pgpy/constants.py", line 20, in <module>
        from .types import FlagEnum
      File "/usr/local/lib/python2.7/dist-packages/pgpy/types.py", line 474, in <module>
        class Dispatchable(six.with_metaclass(MetaDispatchable, PGPObject)):
      File "/usr/lib/python2.7/dist-packages/six.py", line 617, in with_metaclass
        return meta("NewBase", bases, {})
      File "/usr/local/lib/python2.7/dist-packages/pgpy/types.py", line 399, in __new__
        if not hasattr(ncls.__typeid__, '__isabstractmethod__'):
    AttributeError: type object 'NewBase' has no attribute '__typeid__'

**Comment by Commod0re** [comment]
Is the six package installed from the Ubuntu repository (i.e. via `apt-get install python-six`)? Some time ago I found that PGPy does not work well with most versions of six prior to 1.7.2, so installing a newer version of six (>= 1.7.2) should fix it.

**Comment by Commod0re** [comment]
I think this may have to do with the way those versions of six handle `six.with_metaclass` and insert `NewBase` into the class hierarchy. Newer versions appear to do it differently, without modifying the class hierarchy.

**Comment by stoarca** [comment]
Thanks, this solved it. For some reason there was an outdated six.pyc file that six was being imported from.

**Comment by Commod0re** [comment]
I hate when that happens! I'm glad it works now :)
